name: Post Merge to Master

on:
 push:
    branches:
      - main

jobs:
 create_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Get version from config.json
      id: get_version
      run: |
        echo "version=$(jq -r '.__version' resources/config.json)" >> $GITHUB_ENV

    - name: Check if tag exists
      id: check_tag
      run: |
        if git show-ref --tags --verify --quiet "refs/tags/${{ env.version }}"; then
          echo "exists=true" >> $GITHUB_ENV
        else
          echo "exists=false" >> $GITHUB_ENV
        fi

    - name: Create and push tag
      if: env.exists == 'false'
      run: |
        git tag ${{ env.version }}
        git push origin ${{ env.version }}

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.version }}
        release_name: Release ${{ env.version }}
        draft: false
        prerelease: false

 merge_to_staging:
    needs: create_release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout staging branch
      uses: actions/checkout@v2
      with:
        ref: staging

    - name: Fetch all branches
      run: git fetch --all

    - name: Merge master into staging
      run: |
        git checkout staging
        git merge origin/main --no-edit
        git push origin staging
